// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD60FJyuH-9eVHJVJY4oCz5GcVAN3usmtc',
    appId: '1:490293986988:web:12d3359cbaa10b8c5fc109',
    messagingSenderId: '490293986988',
    projectId: 'reddify-19e2e',
    authDomain: 'reddify-19e2e.firebaseapp.com',
    storageBucket: 'reddify-19e2e.appspot.com',
    measurementId: 'G-XD1MB71Z07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyux1b-5-EOWdhcG8wSlc446N_zoaxUSA',
    appId: '1:490293986988:android:4239a822e3e565075fc109',
    messagingSenderId: '490293986988',
    projectId: 'reddify-19e2e',
    storageBucket: 'reddify-19e2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhs4KhDyW6TKtW7NowZz5b6oSL6gtVPMM',
    appId: '1:490293986988:ios:5cf49ac31bef5b015fc109',
    messagingSenderId: '490293986988',
    projectId: 'reddify-19e2e',
    storageBucket: 'reddify-19e2e.appspot.com',
    iosBundleId: 'com.example.reddifyApp',
  );
}
